### ISSUE TITLE
Some files refer to an include license file that is not included

### ISSUE THREAD

**Issue by basak** [juju/testing#32]
`checkers/deepequal.go` and `checkers/deepequal_test.go` refer to "a BSD-style
license that can be found in the LICENSE file" but one is not included. AFAICT, these files cannot be reproduced in this repository without complying with the upstream golang license, which requires the text to be reproduced.

Please can you copy the golang LICENSE file into this repository, and make it clear that these two files apply this license?

**Comment by basak** [comment]
Copied to https://bugs.launchpad.net/juju-core/+bug/1416430

**Comment by johnweldon** [comment]
Pull request #49
